/**
 * Enums compartidos entre api / mobile / admin.
 * Deben mantenerse en sincronía con `apps/api/prisma/schema.prisma`.
 */

export enum UserRole {
  USER = 'USER',
  CREATOR = 'CREATOR',
  PRIEST_VERIFIED = 'PRIEST_VERIFIED',
  ORG_VERIFIED = 'ORG_VERIFIED',
  MODERATOR = 'MODERATOR',
  EDITOR = 'EDITOR',
  SUPPORT = 'SUPPORT',
  ANALYST = 'ANALYST',
  SUPER_ADMIN = 'SUPER_ADMIN',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  BANNED = 'BANNED',
  DELETED = 'DELETED',
}

export enum AuthProvider {
  EMAIL = 'EMAIL',
  GOOGLE = 'GOOGLE',
  APPLE = 'APPLE',
}

export enum DeviceType {
  IOS = 'IOS',
  ANDROID = 'ANDROID',
  WEB = 'WEB',
}

export enum VideoStatus {
  UPLOADING = 'UPLOADING',
  PROCESSING = 'PROCESSING',
  READY = 'READY',
  FAILED = 'FAILED',
}

export enum VideoVisibility {
  PUBLIC = 'PUBLIC',
  FOLLOWERS = 'FOLLOWERS',
  PRIVATE = 'PRIVATE',
  DRAFT = 'DRAFT',
}

export enum ModerationStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  FLAGGED = 'FLAGGED',
}

export enum ContentCategory {
  PRAYER = 'PRAYER',
  BIBLE = 'BIBLE',
  SAINTS = 'SAINTS',
  JESUS = 'JESUS',
  FORMATION = 'FORMATION',
  TESTIMONY = 'TESTIMONY',
  SACRAMENTS = 'SACRAMENTS',
  YOUTH = 'YOUTH',
  FAMILY = 'FAMILY',
  MUSIC = 'MUSIC',
  CHURCH_HISTORY = 'CHURCH_HISTORY',
  OTHER = 'OTHER',
}

export enum ReportTargetType {
  VIDEO = 'VIDEO',
  COMMENT = 'COMMENT',
  USER = 'USER',
  PRAYER_INTENTION = 'PRAYER_INTENTION',
}

export enum ReportReason {
  SPAM = 'SPAM',
  HARASSMENT = 'HARASSMENT',
  HATE_SPEECH = 'HATE_SPEECH',
  THREATS = 'THREATS',
  SEXUAL_CONTENT = 'SEXUAL_CONTENT',
  ILLEGAL_CONTENT = 'ILLEGAL_CONTENT',
  MISINFORMATION = 'MISINFORMATION',
  IMPERSONATION = 'IMPERSONATION',
  DANGEROUS_CONTENT = 'DANGEROUS_CONTENT',
  COPYRIGHT = 'COPYRIGHT',
  OTHER = 'OTHER',
}

export enum ReportStatus {
  OPEN = 'OPEN',
  IN_REVIEW = 'IN_REVIEW',
  RESOLVED = 'RESOLVED',
  DISMISSED = 'DISMISSED',
}

export enum VerificationType {
  PRIEST = 'PRIEST',
  RELIGIOUS = 'RELIGIOUS',
  CATECHIST = 'CATECHIST',
  PARISH = 'PARISH',
  DIOCESE = 'DIOCESE',
  ORGANIZATION = 'ORGANIZATION',
  CREATOR = 'CREATOR',
}

export enum VerificationStatus {
  PENDING = 'PENDING',
  IN_REVIEW = 'IN_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum NotificationType {
  PRAYER_REMINDER = 'PRAYER_REMINDER',
  SAINT_OF_THE_DAY = 'SAINT_OF_THE_DAY',
  CHALLENGE_PROGRESS = 'CHALLENGE_PROGRESS',
  GOSPEL_OF_THE_DAY = 'GOSPEL_OF_THE_DAY',
  NEW_FOLLOWER = 'NEW_FOLLOWER',
  CREATOR_NEW_VIDEO = 'CREATOR_NEW_VIDEO',
  COMMENT_REPLY = 'COMMENT_REPLY',
  VIDEO_LIKED = 'VIDEO_LIKED',
  MODERATION_UPDATE = 'MODERATION_UPDATE',
  SYSTEM = 'SYSTEM',
}

export enum FaithPathObjective {
  GET_CLOSER_TO_JESUS = 'GET_CLOSER_TO_JESUS',
  START_PRAYING = 'START_PRAYING',
  KNOW_THE_BIBLE = 'KNOW_THE_BIBLE',
  KNOW_THE_SAINTS = 'KNOW_THE_SAINTS',
  LEARN_CATHOLICISM = 'LEARN_CATHOLICISM',
  RETURN_TO_CHURCH = 'RETURN_TO_CHURCH',
  IMPROVE_SPIRITUAL_LIFE = 'IMPROVE_SPIRITUAL_LIFE',
  FIND_COMMUNITY = 'FIND_COMMUNITY',
  LIVE_FAITH_AS_FAMILY = 'LIVE_FAITH_AS_FAMILY',
}

export enum PrayerCategoryKey {
  MORNING = 'MORNING',
  NIGHT = 'NIGHT',
  ROSARY = 'ROSARY',
  BEFORE_SLEEP = 'BEFORE_SLEEP',
  GRATITUDE = 'GRATITUDE',
  FORGIVENESS = 'FORGIVENESS',
  FAMILY = 'FAMILY',
  SICKNESS = 'SICKNESS',
  DIFFICULT_TIMES = 'DIFFICULT_TIMES',
  THANKSGIVING = 'THANKSGIVING',
}

export enum Testament {
  OLD = 'OLD',
  NEW = 'NEW',
}

export enum AdminAuditAction {
  USER_SUSPENDED = 'USER_SUSPENDED',
  USER_BANNED = 'USER_BANNED',
  USER_REINSTATED = 'USER_REINSTATED',
  VIDEO_REMOVED = 'VIDEO_REMOVED',
  VIDEO_RESTORED = 'VIDEO_RESTORED',
  REPORT_RESOLVED = 'REPORT_RESOLVED',
  CREATOR_VERIFIED = 'CREATOR_VERIFIED',
  CREATOR_REJECTED = 'CREATOR_REJECTED',
  CHALLENGE_CREATED = 'CHALLENGE_CREATED',
  CATEGORY_UPDATED = 'CATEGORY_UPDATED',
  CONTENT_FEATURED = 'CONTENT_FEATURED',
  NOTIFICATION_BROADCAST = 'NOTIFICATION_BROADCAST',
}

export const SUPPORTED_LOCALES = ['es', 'en'] as const;
export type SupportedLocale = (typeof SUPPORTED_LOCALES)[number];
